packages/rps-poc/src/wallet/utils/signing-utils.ts
At the moment, bot addresses used for communication through Firebase are not checksummed. This small PR converts the opponent address to a checksummed format before comparing the address to the recovered address from a signature.
This PR (along with a few changes in the bot code base) fixes https://zube.io/magmo/client-wallet/c/364.
=> Checksum address for signature verification

.circleci/config.yml, packages/rps-poc/package.json, packages/wallet/package.json
Addresses #32 
It looks like running with `runInBand` and limiting the `concurrency` to 2 can address memory errors/ processes being killed.
=> Get CircleCI working

packages/rps/src/redux/message-service/saga.ts, packages/wallet-client/src/messages-to-wallet.ts, packages/wallet-client/src/wallet-events.ts, packages/wallet-client/src/wallet-functions.ts, packages/wallet/src/redux/reducers/__tests__/opening.test.ts, packages/wallet/src/redux/reducers/opening.ts
Addresses #63.
Instead of returning failure/success messages for opening a channel I removed the Channel Events and the `openChannel` function since they're not actually used in the wallet at all.
I've also modified the opening reducer so we throw errors instead of failing silently.
=> Remove unused open/close channel and throw errors in opening stage

packages/rps/src/containers/NavigationBarContainer.tsx, packages/rps/src/containers/SiteContainer.tsx, packages/rps/src/redux/global/actions.ts, packages/rps/src/redux/global/reducer.ts, packages/rps/src/redux/global/state.ts, packages/rps/src/redux/message-service/saga.ts, packages/rps/src/redux/reducer.ts, packages/wallet-client/src/wallet-events.ts, packages/wallet-client/src/wallet-functions.ts
With this PR, `displayOutbox` is unused (as far as I can tell). Do we want to keep the wiring for `displayOutbox` around for future features?
=> App is responsible for toggling wallet visibility

packages/wallet/src/containers/Initializing.tsx, packages/wallet/src/containers/Wallet.tsx, packages/wallet/src/redux/actions/index.ts, packages/wallet/src/redux/reducers/__tests__/initializing.test.ts, packages/wallet/src/redux/reducers/initializing.ts, packages/wallet/src/redux/reducers/opening.ts, packages/wallet/src/redux/sagas/key-loader.ts, packages/wallet/src/redux/store.ts, packages/wallet/src/states/initializing.ts
I've fixed the issue with the app crashing when `redux dev tools` is not installed.
I've also added a basic pop up in the wallet if metamask is not installed or has does not have permissions on the wallet domain.
Ideally we'd want to just let the `onClick` metamask permissions to work with the iframe as well but I'm not sure how to get that working with the cross domain iframe. So for now we'll just show a message pop up.
=> Handle devtools not being installed and metamask permissions errors

packages/wallet/src/components/TransactionFailed.tsx, packages/wallet/src/containers/Challenging.tsx, packages/wallet/src/containers/Closing.tsx, packages/wallet/src/containers/Funding.tsx, packages/wallet/src/containers/Responding.tsx, packages/wallet/src/containers/Withdrawing.tsx, packages/wallet/src/redux/actions/index.ts, packages/wallet/src/redux/reducers/__tests__/challenging.test.ts, packages/wallet/src/redux/reducers/__tests__/closing.test.ts, packages/wallet/src/redux/reducers/__tests__/funding.test.ts, packages/wallet/src/redux/reducers/__tests__/responding.test.ts, packages/wallet/src/redux/reducers/__tests__/withdrawing.test.ts, packages/wallet/src/redux/reducers/challenging.ts, packages/wallet/src/redux/reducers/closing.ts, packages/wallet/src/redux/reducers/funding.ts, packages/wallet/src/redux/reducers/responding.ts, packages/wallet/src/redux/reducers/withdrawing.ts, packages/wallet/src/redux/sagas/transaction-sender.ts, packages/wallet/src/states/challenging.ts, packages/wallet/src/states/closing.ts, packages/wallet/src/states/funding.ts, packages/wallet/src/states/responding.ts, packages/wallet/src/states/withdrawing.ts
Whenever a transaction submission fails (IE: user rejects a transaction) we now catch that and allow then to retry the transaction.
=> Add retry for transaction failure

packages/wallet/src/__stories__/index.tsx, packages/wallet/src/components/withdrawing/SelectAddress.tsx, packages/wallet/src/containers/Withdrawing.tsx, packages/wallet/src/redux/reducers/__tests__/withdrawing.test.ts, packages/wallet/src/redux/reducers/withdrawing.ts, packages/wallet/src/states/shared.ts, packages/wallet/src/states/withdrawing.ts
Addresses #119.
We now withdraw to the user's current metamask address. We show the user this address and they can change their account before approving the withdraw.
=> Sent funds to metamask account address

packages/wallet/package.json
Change the wallet to use port 8503 to prevent issues with `circleCI`. We probably want a nicer fix for this in the future but this should help with the flickering tests for now.
=> Move wallet to use 8503 for ganache for tests

packages/rps/config/webpack.config.js, packages/rps/src/__stories__/index.tsx, packages/rps/src/containers/SiteContainer.tsx, packages/rps/tslint.json, packages/tictactoe/config/webpack.config.js, packages/tictactoe/src/containers/SiteContainer.tsx, packages/tictactoe/tslint.json, packages/wallet/config/webpack.config.js, packages/wallet/src/redux/reducers/__tests__/closing.test.ts, packages/wallet/src/redux/reducers/__tests__/withdrawing.test.ts, packages/wallet/src/redux/reducers/challenging.ts, packages/wallet/src/redux/reducers/closing.ts, packages/wallet/src/redux/reducers/funding.ts, packages/wallet/src/redux/reducers/responding.ts, packages/wallet/tslint.json
Fixes #176.
The bot was sending a message that we didn't expect and since we lacked the `break` we would cascade into the next case statement and transition to the wrong state.
=> Properly exit case statement if its not message we expect

packages/wallet/src/redux/sagas/message-listener.ts
Fixes #175.
Filter events so any wallet events get buffered in the channel.
=> Filter for wallet events

packages/rps/src/containers/SiteContainer.tsx, packages/rps/src/redux/login/actions.ts, packages/rps/src/redux/login/saga.ts, packages/tictactoe/src/containers/SiteContainer.tsx, packages/tictactoe/src/redux/login/actions.ts, packages/tictactoe/src/redux/login/saga.ts
Fixes #170 .
Ideally I think the `wallet-client` library would wait for the iFrame to load but that would change the `createWalletIframe` function into an `async` function which makes it more awkward to integrate into a react component.
=> Wait for iFrame to load

packages/wallet/src/redux/reducers/__tests__/opening.test.ts, packages/wallet/src/redux/reducers/opening.ts
Fixes #181.
The wallet can now be initialized multiple times before channel is open. This allows the wallet to be initialized for a different user before being used.
=> Allow the wallet to be initialized repeatedly before a channel is open

packages/tictactoe/src/core/results.ts
without this, you will see "Game Over!" instead of "Choose Move" or "Wait for opponent" in the bottom status bar.
=> shifting imperatives by 2

packages/wallet/src/redux/reducers/__tests__/responding.test.ts, packages/wallet/src/redux/reducers/responding.ts
Partially fixes #200.
We now handle a `BLOCK_MINED` action when submitting a response transaction or when a response transaction fails.
Ideally we should be able to tell by the metamask failure why the  the transaction failed and alert the user that the challenge has expired. Unfortunately  the  errors that come back from metamask isn't very informative, and seems to differ between the beta version and the regular version.
=> Handle challenge expiry when trying to respond

packages/wallet/src/__stories__/index.tsx
Otherwise the Wallet container switch is not fed the correct `stage`, and we fall through to the default case every time.
=> fix storybook by embedding channel states in a wallet state

packages/magmo-wallet-client/package.json, packages/rps/yarn.lock
run-s was responsible for some unexpected behaviour, where upon running `npx lerna bootstrap` *all* packages were getting a `prettier:check`, `lint` and `build`, despite these commands appearing as if they should be silo-ed to the `magmo-wallet-client` package. 
In particular this fix will decouple bootstrapping from any build issues in TTT, including an existing issue in that package when targeting 'development' that prevents it from compiling. 
Thanks to @andrewgordstewart and @kerzhner for help troubleshooting.
=> remove run-s, run npx lerna bootstrap

packages/wallet/notes/indirect_funding_proposal.md
- The application channel is always X, never A.
- Objects referenced by their absolute position in the state tree.
- state machine for indirectFunding allows transitions from WAIT_FOR_CONSENSUS back to itself
- added a couple of explanatory sentences which (if correct) I would have found useful for understanding
=> a few typos and other tweaks

packages/wallet/src/redux/__tests__/coordinator.test.ts, packages/wallet/src/redux/__tests__/helpers.ts, packages/wallet/src/redux/__tests__/initialized.test.ts, packages/wallet/src/redux/channelState/funding/__tests__/funding.test.ts, packages/wallet/src/redux/channelState/funding/reducer.ts, packages/wallet/src/redux/fundingState/directFunding/__tests__/directFunding.test.ts, packages/wallet/src/redux/fundingState/directFunding/reducer.ts, packages/wallet/src/redux/outbox/__tests__/reducer.test.ts, packages/wallet/src/redux/outbox/reducer.ts, packages/wallet/src/redux/outbox/state.ts, packages/wallet/src/redux/sagas/saga-manager.ts, packages/wallet/src/redux/state.ts
To get wallet development started again, we need to figure out how to coordinate state updates in the wallet.
This PR removes the `actionOutbox`, cutting the existing communication between branches of the redux state.
This communication needs to be replaced with a "coordinator" that responds to, eg., a `FUNDING_RECEIVED_EVENT` which completely funds a channel by updating both the funding state (based on the action) and the channel state (based on the updated funding state).
There is one failing test, though to cover the existing wallet requirements, more tests are needed. The initialized reducer needs to be rewritten to make this test pass.
Proposed implementations of the coordinators can be based on this branch.
=> Remove actionOutbox

packages/magmo-wallet-client/src/index.ts, packages/magmo-wallet-client/src/wallet-events.ts, packages/magmo-wallet-client/src/wallet-functions.ts, packages/magmo-wallet-client/src/wallet-instructions.ts, packages/magmo-wallet-client/src/wallet-types.ts, packages/rps/src/redux/message-service/saga.ts, packages/rps/src/redux/message-service/state.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/channelState/actions.ts, packages/wallet/src/redux/channelState/closing/__tests__/closing.test.ts, packages/wallet/src/redux/channelState/closing/reducer.ts, packages/wallet/src/redux/channelState/funding/__tests__/funding.test.ts, packages/wallet/src/redux/channelState/funding/reducer.ts, packages/wallet/src/redux/channelState/reducer.ts, packages/wallet/src/redux/outbox/__tests__/reducer.test.ts, packages/wallet/src/redux/sagas/message-listener.ts
This is based on Andrew's work in  #272  and my transaction  work in #270 .
- There is no longer separate methods for communicating commitments and messages to a wallet. There is only `relayWalletMessage` and `messageReceived`.
- Wallet messages now include `channelId` and `procedure`.
- Wallet messages are encapsulated in a `WalletMessage` object so the application can blindly relay the message without knowing the contents.
- `RPS` has been updated to the latest wallet messaging changes.
=> Update Wallet Messages to have a process and channelId

packages/wallet/src/redux/funding/indirect-funding/player-b/state.ts
Added player B states for `indirect-funding`. This assumes that there is no strategy negotiation. 
closes #281
=> Indirect Funding Player B states

packages/wallet/src/__stories__/index.tsx, packages/wallet/src/containers/Funding.tsx, packages/wallet/src/redux/channelState/funding/__tests__/funding.test.ts, packages/wallet/src/redux/channelState/funding/reducer.ts, packages/wallet/src/redux/channelState/funding/state.ts, packages/wallet/src/redux/internal/actions.ts
The vision is that `channelState` funding reducer is shared between application and ledger channels. At the moment, wallet display logic is part of the `FUNDING` stage. The proposal is that the `FUNDING` stage will no longer be responsible for display logic. The funding `procedure` (direct or indirect) will decide when user approval or action is needed **before** the funding stage is entered. Also, currently, user action is requested for acknowledgment of funding success or failure. Once again, the funding `procedure` will handle this.
At the moment, `DIRECT_FUNDING_CONFIRMED` action is part of the `FUNDING` stage reducer. The `FUNDING` stage will be agnostic of the type of funding that funds a channel.
=> channelState funding reducer for both ledger and application channels 

packages/wallet/src/__stories__/index.tsx, packages/wallet/src/containers/Funding.tsx, packages/wallet/src/redux/channel-state/funding/__tests__/funding.test.ts, packages/wallet/src/redux/channel-state/funding/reducer.ts, packages/wallet/src/redux/channel-state/funding/state.ts, packages/wallet/src/redux/channel-state/opening/__tests__/opening.test.ts, packages/wallet/src/redux/channel-state/opening/reducer.ts
The `channelState` reducer now transitions from the opening stage directly to the `WAIT_FOR_FUNDING_AND_POST_FUND_SETUP` state. This is further fallout from the idea that `channelState` tracks only the state of a channel and nothing related to user approvals/acknowledgements or wallet display.
=> channelState reducer: removing wait for funding request

packages/wallet/src/redux/channel-state/__tests__/channel-state.test.ts, packages/wallet/src/redux/channel-state/reducer.ts
Allows for handling actions for ledger Channel which would of been ignored based on the `activeAppChannelId`
Fixes #310
=> Route actions in the channel reducer based on action channelId/commitment

packages/wallet/src/containers/closing.tsx, packages/wallet/src/redux/channel-state/closing/__tests__/closing.test.ts, packages/wallet/src/redux/channel-state/closing/reducer.ts, packages/wallet/src/redux/channel-state/closing/state.ts, packages/wallet/src/redux/channel-state/withdrawing/__tests__/withdrawing.test.ts, packages/wallet/src/redux/channel-state/withdrawing/reducer.ts
I am working to remove the `WaitForChannel` channel state, which we no-longer need now we have initializing channels. The `WaitForChannel` state is the only `ChannelStatus` without a channel id, which is a barrier when trying to write utilities that act on channels.
=> Transition to Finalized instead of WaitForChannel

packages/magmo-wallet-client/src/wallet-types.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/channel-state/closing/reducer.ts, packages/wallet/src/redux/channel-state/funding/__tests__/funding.test.ts, packages/wallet/src/redux/channel-state/funding/reducer.ts, packages/wallet/src/redux/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/indirect-funding/reducer-helpers.ts, packages/wallet/src/redux/outbox/__tests__/reducer.test.ts, packages/wallet/src/redux/sagas/message-listener.ts
Switch `COMMITMENT_RECEIVED`/`MESSAGE_RECEIVED` to use `processId`.
This allows the `COMMITMENT_RECEIVED` action to be passed into the `channelStateReducer` and have it correctly deduce the channelId
=> Switch Message actions to use processId

packages/wallet/src/__stories__/index.tsx, packages/wallet/src/contract-tests/adjudicator-events.test.ts, packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/redux/__tests__/initialized.test.ts, packages/wallet/src/redux/__tests__/selectors.test.ts, packages/wallet/src/redux/__tests__/test-scenarios.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/channel-state/__tests__/channel-state.test.ts, packages/wallet/src/redux/channel-state/actions.ts, packages/wallet/src/redux/channel-state/challenging/__tests__/challenging.test.ts, packages/wallet/src/redux/channel-state/challenging/reducer.ts, packages/wallet/src/redux/channel-state/running/__tests__/running.test.ts, packages/wallet/src/redux/channel-state/running/reducer.ts, packages/wallet/src/redux/direct-funding-store/__tests__/direct-funding.test.ts, packages/wallet/src/redux/direct-funding-store/direct-funding-state/actions.ts, packages/wallet/src/redux/direct-funding-store/direct-funding-state/reducer.ts, packages/wallet/src/redux/indirect-funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/indirect-funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/reducer.ts, packages/wallet/src/redux/sagas/adjudicator-watcher.ts, packages/wallet/src/redux/sagas/saga-manager.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/redux/state.ts
I've added the beginning of the `processState` with a `channelIdsToMonitor`. The adjudicator watcher now checks that state(via a selector) and dispatches actions with the correct process Id.
=> Adjudicator Watcher now checks state for processes to alert

packages/wallet/src/redux/protocols/index.ts
The Protocol reducer signature now accepts protocolState and sharedData as separate args.
=> accept  separate args

packages/magmo-wallet-client/src/wallet-types.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/channel-state/closing/__tests__/closing.test.ts, packages/wallet/src/redux/channel-state/funding/__tests__/funding.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/reducer-helpers.ts, packages/wallet/src/redux/sagas/message-listener.ts
Right now, no messages should arrive that don't have a `processId`, so I semi-arbitrarily opted to throw an error to handle that case.
=> WalletMessagePayload has either a processId or a protocol

packages/wallet/notes/action-routing.md
As mentioned in https://github.com/magmo/apps/pull/353#pullrequestreview-226382469, I realised yesterday that `processId` alone probably isn't enough to route actions. The `processId` will get you to the process but the protocol might then need more information to route the action to the correct sub-protocol (example: if you have a protocol that submits multiple blockchain transactions and needs to identify which one the confirmation is for). This set of notes outline the problem and propose a solution.
=> Action routing notes

packages/wallet/package.json
Clear contracts before build/start to work around the `error: Returned values aren't valid, did it run Out of Gas?` that truffle generates when  trying to compile with existing artifacts.
I'm confirmed that this issue is present before https://github.com/magmo/apps/pull/368 so it doesn't look related to recent changes. It looks like it might be a bug in web3.js version that truffle is using (see https://github.com/ethereum/web3.js/issues/2492)
I've also looked at upgrading truffle but I saw the same error. I've created #375 in the backlog so we can revisit this and see if a later version of truffle addresses this (or investigate further if we're causing it somehow).
resolves #371
=> Clear contracts before start/build

packages/wallet/.vscode/launch.json
Fix the jest all debug entry in launch.json (since there is no `scripts/test.js`)
=> Fix Jest All debug config

packages/wallet/src/__stories__/b-dummy-wallet-states.ts, packages/wallet/src/redux/protocols/defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/defunding/actions.ts, packages/wallet/src/redux/protocols/defunding/container.tsx, packages/wallet/src/redux/protocols/defunding/readme.md, packages/wallet/src/redux/protocols/defunding/reducer.ts, packages/wallet/src/redux/protocols/defunding/state.ts, packages/wallet/src/redux/protocols/helpers.ts, packages/wallet/src/redux/protocols/index.ts, packages/wallet/src/redux/protocols/indirect-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/withdrawing/actions.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/redux/state.ts
A protocol responsible for defunding a channel. Based on the channel type it delegates to either the withdrawal protocol or ledger de-funding protocol.
Once the the ledger de-funding protocol is completed this protocol might need to be revisited and slightly tweaked.
No stories were created as there are no unique views for the protocol
Fixes #396
=> De-Funding Protocol

packages/wallet/src/redux/protocols/challenging/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/responding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/transaction-submission/__tests__/index.ts, packages/wallet/src/redux/protocols/withdrawing/__tests__/scenarios.ts
This PR adds `preSuccessState`, `preFailureState`, `successTrigger` and `failureTrigger` exports from the `transaction-submission/__tests__`. Other protocols can use these to simulate the sub-protocol completing successfully or failing.
Assuming the format here is ok, we should probably make sure every protocol export these states and actions.
=> Export success/failure states and triggers from transaction-submission

packages/rps/contracts/RockPaperScissorsGame.sol, packages/rps/package.json, packages/rps/src/contract-tests/rock-paper-scissors.test.ts, packages/rps/src/core/test-scenarios.ts, packages/rps/yarn.lock
This should mean less code duplication, and make it slightly easier to audit the contract. It was also an excuse to revisit the contract tests: I added one for resolutions being changed incorrectly. I was about to do the same for the 'integer overflow prevented' check, but realised that I did not understand why it has the name it does.
It seems clear that both players should have enough funds to pay the stake to the winner if they lose -- but the message in the relevant `require` statement wasn't doing much justice to that. 
Can anyone enlighten me about the overflow? If a user's allocation has overflowed, it seems to me that we have far bigger problems than safely starting a new game...
=> use function modifiers in the RPS contract

packages/wallet/src/redux/protocols/challenging/readme.md, packages/wallet/src/redux/protocols/direct-funding/__tests__/index.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/direct-funding/components/funding-step.tsx, packages/wallet/src/redux/protocols/direct-funding/container.tsx, packages/wallet/src/redux/protocols/direct-funding/readme.md, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/protocols/direct-funding/state.ts
This work is driven by the need to have success and failure scenarios from the direct-funding protocol, in order to test the indirect-funding protocol. This PR:
* Adds the failure case to direct-funding
* Transitions to this state in the case of a failed transaction
* Exports the pre-success state, pre-failure state and the success/failure triggers for use in testing other protocols.
The failure case is very basic and will need revisiting. As currently written, if the transaction fails and one player abandons, the other player will be stuck.
=> Export pre-success and pre-failure scenarios from direct-funding

packages/wallet/src/redux/protocols/funding/index.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-a/actions.ts, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/states.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-b/actions.ts, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/states.ts
Two choices were made here:
A. the opponent's messaging address is stored directly on the protocol state, as an alternative to extracting the participant's _signing_ address from the channel store
B. player A sends an action to player B, so that player B's top level reducer can, if they wish, extract the action from the message and route it to a process' reducer.
I'd like feedback on these two choices before moving forward.
=> Player A sends funding strategy to player B

packages/wallet/scripts/start.js, packages/wallet/src/containers/initialized.tsx, packages/wallet/src/redux/__tests__/initialized.test.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/adjudicator-state/reducer.ts, packages/wallet/src/redux/channel-state/__tests__/channel-state.test.ts, packages/wallet/src/redux/channel-state/reducer.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/redux/protocols/funding/actions.ts, packages/wallet/src/redux/protocols/funding/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/states.ts, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/states.ts, packages/wallet/src/redux/protocols/funding/reducer.ts, packages/wallet/src/redux/protocols/funding/states.ts, packages/wallet/src/redux/protocols/indirect-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/actions.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/reducer.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts, packages/wallet/src/redux/reducer.ts, packages/wallet/src/redux/sagas/message-listener.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/redux/state.ts, packages/wallet/src/redux/types.ts
Changes to get the RPS app functioning with the changes to the wallet. The goal is to be able to get funding working. This PR gets to point of displaying the `FundingContainer` to the user. Currently its empty but when the Funding views are completed it should show the approval screen.
Resolves #409 
Changes:
- Fixed start script so the wallet wouldn't use pre-built artifacts when targeting a dev network.
- Fixed infinite loop caused by the channelstate reducer constantly generating sig-failed actions.
- Added routing and switched the root reducer to initialize/delegate to the funding reducer.
- Trigger the correct FundingRequested Action
- Show Wallet when funding starts.
- Added a Funding Container that routes to PlayerA/PlayerB container
=> Changes to get Funding working from RPS

packages/wallet/src/components/funding/approve-strategy.tsx, packages/wallet/src/components/funding/choose-strategy.tsx, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/container.tsx
Adds funding views, except when in WAIT_FOR_FUNDING.
I opted to use the `ApproveX` component in the `ChooseStrategy` component for now, since our goal is to get some form of funding working -- offering a choice will come later, with some extra UI work.
=> Funding views

packages/wallet/src/redux/protocols/indirect-defunding/readme.md
Indirect de-funding reducer, scenarios and tests. This assumes that player A will always go first. There is an open issue #412 to address this.
The views and stories will be handled in #411.
Fixes #397
=> Ledger De-Funding

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/protocols/concluding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/concluding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/concluding/actions.ts, packages/wallet/src/redux/protocols/concluding/container.tsx, packages/wallet/src/redux/protocols/concluding/readme.md, packages/wallet/src/redux/protocols/concluding/reducer.ts, packages/wallet/src/redux/protocols/concluding/states.ts, packages/wallet/src/redux/protocols/defunding/__tests__/index.ts, packages/wallet/src/redux/protocols/defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/defunding/actions.ts, packages/wallet/src/redux/protocols/defunding/container.tsx, packages/wallet/src/redux/protocols/defunding/index.ts, packages/wallet/src/redux/protocols/defunding/readme.md, packages/wallet/src/redux/protocols/defunding/reducer.ts, packages/wallet/src/redux/protocols/defunding/states.ts, packages/wallet/src/redux/protocols/index.ts, packages/wallet/src/utils/commitment-utils.ts
Will close #407.
Conclude commitment
Reference: `channel-states/closing/*`
`Defund` sub-protocol
Reference: `challenging` protocol
Cleaning up
They conclude, not me
Reference: `channel-states/closing/*`
=> Finish off Concluding protocol

packages/wallet/src/redux/__tests__/initialized.test.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/adjudicator-state/reducer.ts, packages/wallet/src/redux/reducer.ts
Added some simple logic so that we update the shared data before calling the protocol reducers.
Right now this only handles `AdjudicatorEventAction`s.
Fixes #435
=> Update shared data before protocol reducers

packages/wallet/src/domain/commitments/index.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/state.ts
Work done on indirect funding.
Here's a brief summary of the changes:
- Changed Player B reducer to call `checkAndInitialize` to initialize the state in the `waitForPrefundSetup`
- Finished up the `handleWaitForPostFundSetup1` in player B reducer.
- Updated player B reducer to update funding state on `protocolState` when in the `waitForDirectFunding` state. (Might be worth creating a test that would catch this)
- Various other changes in the player B reducer to get tests passing.
- Start on player A reducer to get some of the tests passing. `Initialize`, `handlePreFundSetup1`, and `handleWaitForDirectFunding` are now written and passing tests.
=> Indirect Funding Work

packages/wallet/src/communication/__tests__/test-scenarios.ts, packages/wallet/src/communication/index.ts, packages/wallet/src/components/funding/approve-strategy.tsx, packages/wallet/src/components/funding/choose-strategy.tsx, packages/wallet/src/redux/__tests__/test-scenarios.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/redux/protocols/funding/index.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-a/actions.ts, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/states.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-b/actions.ts, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/states.ts, packages/wallet/src/redux/reducer.ts, packages/wallet/src/utils/commitment-utils.ts
The communication module serves to define the messages that wallets can send to each other. This facilitates server development, which needs to understand.
I also propose that protocols use bespoke actions, like `concludeChannel`. This way, the wallet knows exactly how to route the action. Right now, it seems like the wallet would have to inspect a `CommitmentReceived` action, say "This commitment is a `CONCLUDE` commitment", check if a conclude process is running for the channel, and if not, create a new process running the `Conclude` protocol.
Once accepted, I would contain all referencers to `messageRelayRequested` by the communication module, and then write out the communication test scenarios.
=> Create communication module

.circleci/config.yml, packages/rps/notes/readme.md
This is slightly dangerous if we don't properly use semantic versioning,
since:
A. if rps depends on wallet version 1.0.*
B. and we update the wallet package to version 1.0.1, which includes
a breaking change
then rps tests would fail, but they won't be run on circle.
Note that lerna filters on packages changed since origin/master. For
some reason, circle's `checkout` command fast-forwards the `master`
branch to the branch being tested, and thus no packages are changed
since `master`.
=>  Only test packages changed since master

packages/rps/src/core/rps-commitment-helper.ts, packages/server/src/app/services/rps-commitment.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/reducer.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts
- The `FUNDING_REQUESTED` action starts the `'Funding'` protocol, not the `'IndirectFunding'` protocol
- The actions that choose and accept a strategy are correctly modified
- The `opponentAddress` is correctly set on the funding state
=> Funding protocol fixes

packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/states.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/states.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-funding/state.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts
Simple change so the funding protocol properly initializes the indirect funding sub-protocol and delegates appropriate actions to it.
=> Add Indirect Funding Sub-protocol to funding protocol

packages/wallet/src/redux/__tests__/initialized.test.ts, packages/wallet/src/redux/reducer.ts
This doesn't guarantee uniqueness of process id (perhaps an application decides to open multiple challenges for a given channel) but it's close enough.
=> More unique process ids

packages/rps/src/redux/message-service/saga.ts, packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/domain/two-player-consensus-game/index.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/protocols/direct-funding/state.ts, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/state.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/state.ts, packages/wallet/src/redux/protocols/indirect-funding/reducer.ts, packages/wallet/src/redux/sagas/transaction-sender.ts, packages/wallet/src/utils/transaction-generator.ts
This PR finishes up the player A reducer to get the player A tests passing.
I've also started working on the app to app funding. Currently I've gotten it to the point that the player A deposit gets sent to metamask.
TODO:
Currently the adjudicator watcher relies on `channelsToMonitor` to dispatch events. However there is no mechanism for a protocol reducer to update `channelsToMonitor`. `channelsToMonitor` gets initialized to an empty array which means no `FUNDING_RECEIVED_EVENT` gets dispatched by the adjudicator watcher. Which means the direct funding reducer gets stuck waiting for the `FUNDING_RECEIVED_EVENT`.
We need some way for the indirect funding reducer to update `channelsToMonitor` once we create the ledger channel, so `FUNDING_RECEIVED_EVENT`s get generated. That or we need the …
=> Indirect Funding Updates

packages/wallet/src/contract-tests/adjudicator-events.test.ts, packages/wallet/src/redux/__tests__/selectors.test.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/redux/state.ts
Here is a sketch of a way forward, such that protocol reducers can update some `sharedData` representing which channels we are interested in, which the adjudicator watcher can then use to filter the on chain state that it should mirror. 
This is work towards progressing `indirect-funding` past the funding of the ledger channel, which it cannot currently progress beyond due to a lack of such a mechanism.
=> Use channelSubscriptions

packages/wallet/src/redux/protocols/container.tsx, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-a/container.tsx, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/states.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/funding/player-b/container.tsx, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/states.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts
This gets the happy path of app to app funding working to the point that the wallet returns to the application and players can play a funded game of RPS.
(The PR can be based on `master` once #470 is merged in)
=> Happy Path: App to App funding

packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-defunding/readme.md, packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts, packages/wallet/src/redux/protocols/indirect-defunding/state.ts
Updates the ledger de-funding protocol to work with the recent changes made to the consensus app.
(The PR can be based on master once #471  is merged in)
=> Update Ledger De-funding to work with Consensus App

package.json, packages/server/Procfile, packages/server/package.json, packages/server/yarn.lock
This configuration is not ideal:
- Builds on Heroku take a while.
- Root `package.json` contains Heroku-specific configuration, which is only applicable to the `server` package.
Another approach we can try is using yarn workspaces to see if that speeds up Heroku builds. With yarn workspaces, we would not need the `cacheDirectories` list. We can also try using Docker with Heroku to speed up builds.
=> Heroku monorepo configuration

packages/wallet/.gitignore, packages/wallet/index.ts, packages/wallet/package.json, packages/wallet/src/communication/__tests__/commitments.ts, packages/wallet/src/communication/__tests__/test-scenarios.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/utils/reducer-utils.ts, packages/wallet/tsconfig.json
This PR allows other packages to import code from the wallet package.
By rights, this exported code should live in the `magmo-wallet-common` package, but it's currently a bit spread out in the wallet package.
To more quickly use the code in the `nitro-server` package, exporting it from `index.ts` is a reasonable trade-off. When we refactor the common code into `magmo-wallet-common`, it would only require changing `import * from 'magmo-wallet'` to `import * from 'magmo-wallet-common'` in whatever package is currently using that "common" code.
=> Export code from wallet package

packages/wallet-common/prebuilt-contracts/Commitment.json, packages/wallet-common/prebuilt-contracts/NitroAdjudicator.json, packages/wallet-common/prebuilt-contracts/Rules.json, yarn.lock
Ganache addresses snuck into the prebuilt contracts of the `wallet-common` package.
=> Remove ganache addresses from prebuilt contracts

packages/wallet/src/redux/__tests__/helpers.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts
If player B received `postFundSetup0` before the channel is funded the commitment was not stored anywhere.
This means that after the channel gets funded when Player B tries to send out `postFundSetup1` it fails since we're trying to transition from `preFundSetup0` to `postFundSetup1`.
To fix this we now update the channel state with the `postFundSetup0` commitment even if the channel is not funded yet.
=> Fix Direct Funding Race Condition

packages/wallet/package.json, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/protocols/challenging/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/challenging/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/challenging/__tests__/stories.tsx, packages/wallet/src/redux/protocols/challenging/actions.ts, packages/wallet/src/redux/protocols/challenging/container.tsx, packages/wallet/src/redux/protocols/challenging/readme.md, packages/wallet/src/redux/protocols/challenging/reducer.ts, packages/wallet/src/redux/protocols/challenging/states.ts, packages/wallet/src/redux/protocols/concluding/instigator/readme.md, packages/wallet/src/redux/protocols/concluding/responder/readme.md, packages/wallet/src/redux/protocols/defunding/readme.md, packages/wallet/src/redux/protocols/direct-funding/components/funding-step.tsx, packages/wallet/src/redux/protocols/funding/player-a/__tests__/stories.tsx, packages/wallet/src/redux/protocols/funding/player-b/__tests__/stories.tsx, packages/wallet/src/redux/protocols/responding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/responding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/responding/__tests__/stories.tsx, packages/wallet/src/redux/protocols/responding/actions.ts, packages/wallet/src/redux/protocols/responding/components/wait-for-approval.tsx, packages/wallet/src/redux/protocols/responding/container.tsx, packages/wallet/src/redux/protocols/responding/readme.md, packages/wallet/src/redux/protocols/responding/reducer.ts, packages/wallet/src/redux/protocols/responding/state.ts, packages/wallet/src/redux/reducer.ts, yarn.lock
In the event of a challenge timing out:
Here 'option' means "an offer you can't refuse".
TODO: 
(possibly in a separate PR)
=> Handle challenge timeouts

packages/wallet/src/domain/commitments/__tests__/index.ts, packages/wallet/src/utils/__tests__/commitment-utils.test.ts, packages/wallet/src/utils/commitment-utils.ts
Fixes composeConcludeCommitment so it does not override `appAttributes` with consensus app attributes.
=> Fix composeConcludeCommitment

packages/rps/contracts/RockPaperScissorsGame.sol, packages/rps/src/contract-tests/rock-paper-scissors.test.ts, packages/tictactoe/contracts/TicTacToeGame.sol, packages/tictactoe/src/contract-tests/ttt-game.test.ts
The `destination` field was introduced with Nitro (to allow the a channel to allocate to non-participant addresses) -- but our apps are only safe under the old ForceMove protocol since no checks on `destination` are performed inside `validTransition`. There is an attack where I overwrite `destination` with my own address as the single beneficiary, and I can then transfer more funds than I am entitled to into my own account.
=> Ensure destination field does not change in application channels

packages/rps/src/redux/message-service/saga.ts, packages/wallet/src/redux/protocols/application/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/application/actions.ts, packages/wallet/src/redux/protocols/application/readme.md, packages/wallet/src/redux/protocols/application/reducer.ts, packages/wallet/src/redux/protocols/concluding/instigator/reducer.ts, packages/wallet/src/redux/sagas/adjudicator-watcher.ts, packages/wallet/src/redux/sagas/challenge-watcher.ts, packages/wallet/src/redux/sagas/message-listener.ts, packages/wallet/src/redux/sagas/message-sender.ts
Previously, the mere request for a conclude was wrapping up the application process. Since the instigator can back out, this is undesired behaviour because the application process needs to continue.
Instead, it should 
and only be wrapped up when 
~~As far as I can tell, conclude commitments are not verified (at least not in the same way as regular commitments). There is an open question about exactly where and how to dispatch the action that will wrap up the application process, when the channel is finalized off chain.~~
Message sender and listener sagas will inspect the messages, and conditionally put a new `concluded` action, to be routed to the `Application` process, as appropriate.
=> Allow `Application-` to continue when instigator cancels conclude

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/protocols/advance-channel/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/advance-channel/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/advance-channel/actions.ts, packages/wallet/src/redux/protocols/advance-channel/readme.md, packages/wallet/src/redux/protocols/advance-channel/reducer.ts, packages/wallet/src/redux/protocols/advance-channel/states.ts
This lets the directFunding protocol embed an `advanceChannelState`, by allowing the funding protocol to block sending of commitments until the channel is funded.
=> Add clearedToSend flag to advanceChannelState

packages/wallet/src/redux/sagas/__tests__/message-listener.test.ts, packages/wallet/src/redux/sagas/message-listener.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/utils/contract-utils.ts
Calls `validateTransition` from the `message-listener` whenever receiving a `commitment`.
Fixes #561.
=> Validate Transitions

packages/wallet/notes/index.md, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/redux/protocols/application/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/application/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/application/actions.ts, packages/wallet/src/redux/protocols/application/container.tsx, packages/wallet/src/redux/protocols/application/readme.md, packages/wallet/src/redux/protocols/application/reducer.ts, packages/wallet/src/redux/protocols/application/states.ts, packages/wallet/src/redux/protocols/container.tsx, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/dispute/challenger/index.ts, packages/wallet/src/redux/protocols/dispute/container.tsx, packages/wallet/src/redux/protocols/dispute/index.ts, packages/wallet/src/redux/protocols/dispute/reducer.ts, packages/wallet/src/redux/reducer.ts, packages/wallet/src/redux/sagas/challenge-response-initiator.ts, packages/wallet/src/redux/sagas/challenge-watcher.ts, packages/wallet/src/redux/sagas/message-listener.ts
This PR moves us toward protocols embedding `dispute`, rather than spawning a new `dispute` process. The guiding principle here is that the parent protocol *should* block while the dispute is in progress, and cannot terminate until `dispute` terminates (since `dispute` can resolve in multiple ways, such as a challenge expiring or being responded to).
Current hierarchy on base branch (master):
new hierarchy:
=> Nest Dispute under Application

packages/rps/src/redux/message-service/saga.ts, packages/server/src/app/handlers/handle-new-process-action.ts, packages/server/src/app/handlers/handle-ongoing-process-action.ts, packages/wallet/src/communication/actions.ts, packages/wallet/src/redux/__tests__/helpers.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts, packages/wallet/src/redux/sagas/__tests__/multiple-action-dispatcher.test.ts, packages/wallet/src/redux/sagas/multiple-action-dispatcher.ts
This PR improves the way in which I can relay multiple whitelisted actions to my opponent's wallet. 
The order such actions are `put` is important (for example when I wish to _first_ start a new process in my opponent's wallet, and _then_ for that process to consume a `CommitmentReceived`).
Previously, the actions were queued and then relayed by the app in order: but they might get `put` out of order depending on asynchronous reads/writes to/from firebase.*
In this PR, the actions are batched in an array into a `MultipleRelayableActions` action. This is the only action that is relayed and routed through firebase. A saga running in the recipient wallet then dispatches these batched actions non-concurrently (i.e. in a set order). 
Also included: a helper function for testing this behaviour …
=> Relay multiple actions in an ordered batch

packages/rps/package.json
The [recent change](https://github.com/magmo/force-move-protocol/compare/fmg-core@0.5.6...master#diff-0d7546e635886f7575ca1259253096caL10) to the  `channelID` function at packages/fmg-core/src/channel.ts changed the way that channel addresses are computed. 
Applications (i.e. RPS) should use the same function as the wallet, since their working together relies on consistent `channelId`s.
=> Upgrade fmg-core in rps package

packages/wallet/notes/index.md, packages/wallet/src/redux/protocols/consensus-update/components/wait-for-ledger-update.tsx, packages/wallet/src/redux/protocols/consensus-update/container.tsx, packages/wallet/src/redux/protocols/direct-funding/container.tsx, packages/wallet/src/redux/protocols/existing-ledger-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/__tests__/stories.tsx, packages/wallet/src/redux/protocols/existing-ledger-funding/components/wait-for-ledger-update.tsx, packages/wallet/src/redux/protocols/existing-ledger-funding/components/wait-for-post-fund-setup.tsx, packages/wallet/src/redux/protocols/existing-ledger-funding/container.tsx, packages/wallet/src/redux/protocols/existing-ledger-funding/readme.md, packages/wallet/src/redux/protocols/ledger-top-up/__tests__/stories.tsx, packages/wallet/src/redux/protocols/ledger-top-up/container.tsx, packages/wallet/src/styles/wallet.scss
Add containers and components for `existing-ledger-funding` and it's children (where necessary). 
Many of the screens are only visible for a fraction of a second in the happy path. However, in future we will want to allow for inactivity and challenging, and then they may appear for longer. 
This PR also introduces a way to clip long hex string channel addresses.
Closes #570
=> Existing ledger funding UI

packages/wallet/src/redux/protocols/concluding/instigator/reducer.ts, packages/wallet/src/redux/protocols/concluding/responder/reducer.ts, packages/wallet/src/redux/protocols/consensus-update/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/consensus-update/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/consensus-update/actions.ts, packages/wallet/src/redux/protocols/consensus-update/reducer.ts, packages/wallet/src/redux/protocols/consensus-update/states.ts, packages/wallet/src/redux/protocols/ledger-top-up/reducer.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
As part of the refactor to exchange post fund setups in the `funding`/`newLedgerFunding` protocol I ran into an issue  where ledger updates were coming in early.
To address this I've added `clearedToSend` so the Consensus Update protocol can be started before the commitment arrives and be handled properly.
Related to #593.
=> add Cleared To Send support to Consensus Update Protocol

packages/wallet/tslint.json
TS-lint was failing and outputting an error on build/start. This disables the rule that was causing the failure.
```The 'prefer-for-of' rule threw an error in '/Users/alexgap/code/apps/packages/wallet/src/utils/hex-utils.ts':
TypeError: Cannot read property 'uses' of undefined
at visitForStatement (/Users/alexgap/code/apps/node_modules/tslint/lib/rules/preferForOfRule.js:66:59)
at cb (/Users/alexgap/code/apps/node_modules/tslint/lib/rules/preferForOfRule.js:53:13)
at visitNodes (/Users/alexgap/code/apps/node_modules/typescript/lib/typescript.js:16514:30)
at Object.forEachChild (/Users/alexgap/code/apps/node_modules/typescript/lib/typescript.js:16740:24)
at cb (/Users/alexgap/code/apps/node_modules/tslint/lib/rules/preferForOfRule.js:55:19)
at visitNode …
```
=> TSLint fails on build/start

packages/wallet/src/redux/protocols/indirect-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/new-ledger-channel/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/new-ledger-channel/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/new-ledger-channel/reducer.ts
Funding state was not being set correctly so existing ledger channels were not being found when trying to fund the game with an existing ledger channel.
Fixes #622
=> Correctly set funding state in New Ledger Channel protocol

packages/wallet/src/redux/protocols/consensus-update/__tests__/index.ts, packages/wallet/src/redux/protocols/consensus-update/states.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/states.ts, packages/wallet/src/redux/protocols/indirect-funding/reducer.ts, packages/wallet/src/redux/protocols/ledger-top-up/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/ledger-top-up/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/ledger-top-up/reducer.ts, packages/wallet/src/redux/protocols/ledger-top-up/states.ts, packages/wallet/src/redux/protocols/virtual-funding/__tests__/reducer.test.ts
Two main changes in this PR:
- Refactor Existing Ledger Funding to use Consensus Update
- Start Consensus Update protocol early in Ledger Top Up to handle commitments that might come in before we get a `FUNDING_RECEIVED` event.
Fixes #625
=> Fix Ledger Top Up

packages/wallet/src/redux/protocols/advance-channel/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/advance-channel/reducer.ts, packages/wallet/src/redux/protocols/defunding/reducer.ts, packages/wallet/src/redux/protocols/dispute/reducer.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/wallet/src/redux/protocols/funding/player-a/reducer.ts, packages/wallet/src/redux/protocols/funding/player-b/reducer.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts, packages/wallet/src/redux/protocols/indirect-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-funding/reducer.ts, packages/wallet/src/redux/protocols/ledger-top-up/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/ledger-top-up/reducer.ts, packages/wallet/src/redux/protocols/new-ledger-channel/reducer.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
Many initializers are better off using destructured objects as their arguments. This is less bug-prone -- consider the case where `proposedAllocation` and `proposedDestination` are passed in the wrong order -- and leads to cleaner tests.
Along the way, I removed some extra cruft.
=> Clean up initializers

packages/wallet/src/redux/protocols/new-ledger-channel/reducer.ts
When creating the initial prefund setup for the ledger channel we were setting `proposedAllocation` and `proposedDestination` however according to the consensus rules these must be empty for a consensus (which is the state we start in)
=> Fix Invalid Transition

packages/wallet/src/redux/protocols/concluding/responder/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/defunding/readme.md, packages/wallet/src/redux/protocols/defunding/reducer.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/index.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-defunding/__tests__/stories.tsx, packages/wallet/src/redux/protocols/indirect-defunding/actions.ts, packages/wallet/src/redux/protocols/indirect-defunding/readme.md, packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts, packages/wallet/src/redux/protocols/indirect-defunding/states.ts
This PR does two things:
- Refactors the Indirect De-funding to use AdvanceChannel/ConsensusUpdate to handle sending/receiving commitments
- Add a `ClearedToSend` to allow indirectDefunding to be started early.
This was needed for work on #658
=> Refactor Indirect-Defunding to use AdvanceChannel and ConsensusUpdate

packages/wallet/src/constants.ts, packages/wallet/src/redux/__tests__/helpers.ts, packages/wallet/src/redux/channel-store/channel-state/states.ts, packages/wallet/src/redux/protocols/defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/defunding/actions.ts, packages/wallet/src/redux/protocols/defunding/container.tsx, packages/wallet/src/redux/protocols/defunding/readme.md, packages/wallet/src/redux/protocols/defunding/reducer.ts, packages/wallet/src/redux/protocols/defunding/states.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/indirect-defunding/actions.ts, packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts, packages/wallet/src/redux/protocols/virtual-defunding/__tests__/index.ts, packages/wallet/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/virtual-defunding/container.tsx, packages/wallet/src/redux/protocols/virtual-defunding/index.ts, packages/wallet/src/redux/protocols/virtual-defunding/reducer.ts, packages/wallet/src/redux/protocols/virtual-defunding/states.ts, packages/wallet/src/redux/protocols/virtual-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts, packages/wallet/src/redux/protocols/virtual-funding/states.ts
This gets virtual de-funding integrated into the parent defunding protocol.
It allows for the defunding/withdrawal from a game that has been virtually funded.
This is dependent on #655 #661, #660 and #659 and should only be merged after those.
=> Add Virtual De-Funding to de-funding protocol.

packages/wallet/src/redux/sagas/message-listener.ts
If an app transition was invalid we would throw an error trying to decode the appAttributes of non-consensus rules.
=> Handle invalid app transitions
