magmo/apps

- .circleci/config.yml
- .circleci/run-build-locally.sh
- lerna.json
- package.json
- packages/tictactoe/src/redux/game/reducer.ts
Added a basic CI config file to root that should (hopefully) run `test:ci` on all projects. We'll probably want to update this with some smarts to only test what has been changed later on.
> Get CI running

- packages/rps-poc/src/components/CreatingOpenGameModal.tsx
Addresses https://zube.io/magmo/client-wallet/c/358
> Fix create game message from game buy in to round buy in

- packages/wallet/src/__stories__/index.tsx
- packages/wallet/src/components/WaitForXConfirmation.tsx
- packages/wallet/src/components/responding/WaitForResponseConfirmation.tsx
- packages/wallet/src/containers/Challenging.tsx
- packages/wallet/src/containers/Closing.tsx
- packages/wallet/src/containers/Funding.tsx
- packages/wallet/src/containers/Responding.tsx
- packages/wallet/src/containers/Withdrawing.tsx
- packages/wallet/src/integration-tests/transactions.test.ts
- packages/wallet/src/redux/actions/index.ts
- packages/wallet/src/redux/reducers/__tests__/challenging.test.ts
- packages/wallet/src/redux/reducers/__tests__/closing.test.ts
- packages/wallet/src/redux/reducers/__tests__/funding.test.ts
- packages/wallet/src/redux/reducers/__tests__/responding.test.ts
- packages/wallet/src/redux/reducers/__tests__/withdrawing.test.ts
- packages/wallet/src/redux/reducers/challenging.ts
- packages/wallet/src/redux/reducers/closing.ts
- packages/wallet/src/redux/reducers/funding.ts
- packages/wallet/src/redux/reducers/responding.ts
- packages/wallet/src/redux/reducers/withdrawing.ts
- packages/wallet/src/redux/sagas/transaction-sender.ts
- packages/wallet/src/states/challenging.ts
- packages/wallet/src/states/closing.ts
- packages/wallet/src/states/funding.ts
- packages/wallet/src/states/responding.ts
- packages/wallet/src/states/shared.ts
- packages/wallet/src/states/withdrawing.ts
Addresses https://zube.io/magmo/client-wallet/c/377
> Create real etherscan links based on the transaction hash

- packages/rps-poc/truffle.js
Addresses https://zube.io/magmo/client-wallet/c/381
> Added entry for main so we catch when metamask has main network selected

- .gitignore
- packages/wallet-client/.gitignore
- packages/wallet-client/yarn.lock
- packages/wallet/package.json
Also, changing the ganache port as CircleCi was failing for this earlier.
> Adding node modules to gitignore

- packages/wallet/src/containers/Closing.tsx
- packages/wallet/src/redux/reducers/__tests__/closing.test.ts
- packages/wallet/src/redux/reducers/closing.ts
- packages/wallet/src/states/closing.ts
Send a message to the other player when a player starts closing. 
Addresses #17
> Send message to other player that close has been started

- packages/tictactoe/src/core/test-scenarios.ts
- packages/tictactoe/src/redux/game/__tests__/player-a.test.ts
- packages/tictactoe/src/redux/game/__tests__/player-b.test.ts
- packages/tictactoe/src/redux/game/reducer.ts
Loser := whomever did not play last when a conclusive (win/lose/draw) state is reached.
> [tictactoe] Increase turnNum correctly when playing again in 'loser's' app

- packages/rps/src/redux/game/__tests__/player-b.test.ts
- packages/rps/src/redux/game/reducer.ts
> Store action that comes in while waiting for funding in actionToRetry

- packages/rps/src/redux/message-service/saga.ts
- packages/wallet/src/redux/reducers/closing.ts
Addresses #61.
Throw errors when something goes wrong, instead of failing silently.
> Fix cases where we fail silently

- packages/tictactoe/src/redux/message-service/saga.ts
Fixes https://zube.io/magmo/apps/c/476
> Wallet-client no longer exposes openChannel

- packages/tictactoe/src/components/GameOverPage.tsx
- packages/tictactoe/src/containers/GameContainer.tsx
- packages/tictactoe/src/redux/game/actions.ts
- packages/tictactoe/src/redux/game/reducer.ts
- packages/tictactoe/src/redux/message-service/saga.ts
Addresses https://github.com/magmo/apps/issues/80 . 
It is now possible to continue playing if a challenge is responded to.
> Gk ttt challenge flow

- packages/rps/src/containers/GameContainer.tsx
- packages/rps/src/containers/GameFooterContainer.tsx
- packages/rps/src/redux/game/reducer.ts
- packages/rps/src/redux/game/state.ts
- packages/rps/src/redux/message-service/saga.ts
> Allow challenging in play again

- packages/tictactoe/src/__stories__/index.tsx
- packages/tictactoe/src/containers/NavigationBarContainer.tsx
- packages/tictactoe/src/containers/SiteContainer.tsx
- packages/tictactoe/src/redux/global/actions.ts
- packages/tictactoe/src/redux/global/reducer.ts
- packages/tictactoe/src/redux/global/state.ts
- packages/tictactoe/src/redux/message-service/saga.ts
- packages/tictactoe/src/redux/reducer.ts
Fixes https://github.com/magmo/apps/issues/111
> TTT wallet visibility

- cloudbuild.yaml
- packages/tictactoe/config/webpack.config.js
- packages/tictactoe/src/gateways/firebase.ts
Most of what we need for https://github.com/magmo/apps/issues/123
> get TTT ready for deploy

- packages/rps/config/webpack.config.js
- packages/rps/src/gateways/firebase.ts
- packages/tictactoe/config/webpack.config.js
- packages/tictactoe/src/gateways/firebase.ts
- packages/wallet/config/webpack.config.js
- packages/wallet/gateways/firebase.ts
Reverts magmo/apps#138
My mistake, I didn't realize there was a separate tic tac toe firebase.
> Revert "Set correct firebase sender id for tictactoe"

- packages/wallet/src/components/withdrawing/SelectAddress.tsx
- packages/wallet/src/containers/Closing.tsx
- packages/wallet/src/containers/Withdrawing.tsx
- packages/wallet/src/index.scss
- packages/wallet/src/redux/actions/index.ts
- packages/wallet/src/redux/reducers/__tests__/closing.test.ts
- packages/wallet/src/redux/reducers/closing.ts
- packages/wallet/src/redux/reducers/withdrawing.ts
- packages/wallet/src/states/closing.ts
- packages/wallet/src/styles/select-address.scss
> Use WithdrawAndClose instead of Close to improve user experience

- packages/rps/src/__stories__/index.tsx
- packages/rps/src/components/LoadingPage.tsx
- packages/rps/src/components/MetamaskErrorPage.tsx
- packages/rps/src/containers/SiteContainer.tsx
- packages/rps/src/core/test-scenarios.ts
- packages/tictactoe/src/components/MetamaskErrorPage.tsx
- packages/tictactoe/src/styles/home-page.scss
- packages/tictactoe/src/styles/waiting-room.scss
Fixes #149 , Fixes #146 , Fixes #142 .
> Add storybook to rps and tweak components

- packages/rps/package.json
- packages/rps/src/contract-tests/rock-paper-scissors.test.ts
- packages/rps/src/contract-tests/rps-state.test.ts
- packages/rps/yarn.lock
- packages/tictactoe/package.json
- packages/tictactoe/src/contract-tests/ttt-game.test.ts
- packages/tictactoe/yarn.lock
- packages/wallet/package.json
- packages/wallet/src/contract-tests/transactions.test.ts
- packages/wallet/yarn.lock
> Fix issue 162

- packages/wallet/src/redux/reducers/__tests__/challenging.test.ts
- packages/wallet/src/redux/reducers/challenging.ts
> Hide wallet and send complete challenge message on challenge decline

- packages/rps/src/__stories__/index.tsx
- packages/rps/src/components/LoginErrorPage.tsx
- packages/rps/src/containers/SiteContainer.tsx
- packages/rps/src/redux/login/actions.ts
- packages/rps/src/redux/login/reducer.ts
- packages/rps/src/redux/login/saga.ts
- packages/tictactoe/src/__stories__/index.tsx
- packages/tictactoe/src/components/LoginErrorPage.tsx
- packages/tictactoe/src/containers/SiteContainer.tsx
- packages/tictactoe/src/redux/login/actions.ts
- packages/tictactoe/src/redux/login/reducer.ts
- packages/tictactoe/src/redux/login/saga.ts
> Added basic login error page for when library is not deployed

- packages/rps/config/env.js
- packages/rps/public/index.html
- packages/tictactoe/config/env.js
- packages/tictactoe/public/index.html
- packages/wallet/config/env.js
- packages/wallet/public/index.html
Add a timestamp for build-version. We'll want to improve this with the latest commit hash in the future.
> Add a basic timestamp for build-version

- cloudbuild.yaml
Disable caching of service-worker.js per 
https://github.com/facebook/create-react-app/issues/2440#issuecomment-305522631
> Update build script to disable caching of service-worker.js

- packages/tictactoe/src/__stories__/index.tsx
- packages/tictactoe/src/components/GameFooter.tsx
- packages/tictactoe/src/components/GameOverPage.tsx
- packages/tictactoe/src/containers/GameContainer.tsx
- packages/tictactoe/src/core/results.ts
- packages/tictactoe/src/redux/game/__tests__/player-a.test.ts
- packages/tictactoe/src/redux/game/reducer.ts
- introduce new result types GameOverWin and GameOverLose
- forgo Modal for a simple button so you can still see board and
challenge button
- improve relevant story in storybook
- Fixes #189
> make GameOverPage more like PlayAgain and PlayAgainWait

- packages/magmo-wallet-client/src/messages-to-wallet.ts
- packages/rps/src/redux/game/reducer.ts
Fixes #178, and players may now successfully respond to a challenge in 'play again' as well 'pick move' states.
> Responding to challenges

- packages/rps/src/components/WaitingRoomPage.tsx
- packages/tictactoe/src/__stories__/index.tsx
- packages/tictactoe/src/components/CreatingOpenGameModal.tsx
- packages/tictactoe/src/components/GameFooter.tsx
- packages/tictactoe/src/components/RulesModal.tsx
- packages/tictactoe/src/components/WaitingRoomPage.tsx
- packages/tictactoe/src/styles/rules.scss
> [ttt] rules and roundBuyIn

- packages/rps/src/components/OpenGameCard.tsx
- packages/rps/src/redux/game/reducer.ts
- packages/rps/src/redux/game/state.ts
- packages/rps/src/redux/message-service/saga.ts
- packages/wallet/package.json
- packages/wallet/src/utils/contract-utils.ts
- packages/wallet/yarn.lock
- Use a random channel nonce
- Add helper methods to get holdings/outcome
- Upgrade to adjudicator with updated `transfer`/`overlap`
- Fixed `libaryAddress` getting lost when a players exit to the lobby
- Fix issue where players could not respond to a challenge
> WIP: Nitro Work

- packages/rps/package.json
- packages/rps/src/components/OpenGameCard.tsx
- packages/rps/src/core/rps-commitment.ts
- packages/rps/yarn.lock
- packages/wallet/package.json
- packages/wallet/src/components/responding/AcknowledgeTimeout.tsx
- packages/wallet/src/components/responding/ChooseResponse.tsx
- packages/wallet/src/contract-tests/transactions.test.ts
- packages/wallet/src/redux/reducers/__tests__/withdrawing.test.ts
- packages/wallet/src/redux/reducers/closing.ts
- packages/wallet/src/redux/reducers/withdrawing.ts
- packages/wallet/src/redux/sagas/adjudicator-watcher.ts
- packages/wallet/src/utils/contract-utils.ts
- packages/wallet/src/utils/transaction-generator.ts
- packages/wallet/yarn.lock
- Get challenges working
- Clean up react error log
- Clean up console.logs I left everywhere
> Wallet Work

- packages/wallet/notes/channel_opening.md
The sequence diagram shows midlevel details for opening an application channel funded via a ledger channel.
> Channel opening diagram

- packages/wallet/src/redux/outbox/__tests__/reducer.test.ts
- packages/wallet/src/redux/outbox/reducer.ts
- packages/wallet/src/redux/reducer.ts
Just a small change isolating outbox-specific logic.
> Extract outbox clearing logic

- packages/wallet/notes/indirect_funding_proposal.md
A proposal for how to approach indirect funding.
> Indirect funding proposal

- packages/wallet/src/redux/funding/readme.md
This PR pulls out documentation from Tom's proposal. It does not include (pseudo)code from the proposal. Consult [tom-indirect-funding-spike](https://github.com/magmo/apps/tree/tom-indirect-funding-spike) for the full proposal.
> Funding documentation

- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/indirectFunding/actions.ts
- packages/wallet/src/redux/indirectFunding/playerA/actions.ts
- packages/wallet/src/redux/indirectFunding/playerA/reducer.ts
- packages/wallet/src/redux/indirectFunding/playerB/actions.ts
- packages/wallet/src/redux/indirectFunding/states.ts
- packages/wallet/src/redux/state.ts
This can be filled out with the state machine logic.
> Add a skeleton player A indirect funding reducer.

- packages/wallet/src/redux/indirectFunding/readme.md
Changes from https://github.com/magmo/apps/pull/285 in a separate PR.
> Update state diagrams in readme

- packages/wallet/src/redux/channel-state/state.ts
- packages/wallet/src/redux/state.ts
Am using this on multiple branches, so wanted to get it into master.
> setChannel and setSideEffects on wallet state

- README.md
Our kebab-case convention is not the first thing people need to know when reading about the project ... :stuck_out_tongue:
> Reorder readme

- packages/wallet/src/redux/protocols/index.ts
Adds a protocol reducer interface so we can start implementing it in our protocol reducers.
> Add a Protocol Reducer Interface

- packages/wallet/notes/structuring-the-wallet.md
This PR proposes a solution to the questions that came up at the end of last week around how processes in the wallet should be composed.
> Wallet architecture proposal

- packages/wallet/src/redux/protocols/transaction-submission/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/transaction-submission/components/approve-retry.tsx
- packages/wallet/src/redux/protocols/transaction-submission/components/failure.tsx
- packages/wallet/src/redux/protocols/transaction-submission/components/success.tsx
- packages/wallet/src/redux/protocols/transaction-submission/components/wait-for-confirmation.tsx
- packages/wallet/src/redux/protocols/transaction-submission/components/wait-for-submission.tsx
- packages/wallet/src/redux/protocols/transaction-submission/container.tsx
These views are very basic - more of a placeholder until we figure out what we want the overall user experience to be.
> Transaction submission views

- packages/wallet/src/containers/initialized.tsx
- packages/wallet/src/redux/protocols/indirect-funding/components/approve-funding.tsx
- packages/wallet/src/redux/protocols/indirect-funding/components/funding-step.tsx
- packages/wallet/src/redux/protocols/indirect-funding/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-b/container.tsx
Addressing https://github.com/magmo/apps/pull/378#discussion_r276082839.
> Moving indirect funding UI files

- packages/wallet/src/contract-tests/adjudicator-events.test.ts
- packages/wallet/src/redux/__tests__/initialized.test.ts
- packages/wallet/src/redux/__tests__/selectors.test.ts
- packages/wallet/src/redux/protocols/funding/readme.md
- packages/wallet/src/redux/reducer.ts
- packages/wallet/src/redux/state.ts
This is branched off of resolve-issue-362, which made some changes to `SharedData` etc.
> Resolve issue 361

- packages/wallet/src/redux/__tests__/test-scenarios.ts
- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/protocols/challenging/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/challenging/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/challenging/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/challenging/actions.ts
- packages/wallet/src/redux/protocols/challenging/components/approve-challenge.tsx
- packages/wallet/src/redux/protocols/challenging/components/wait-for-response-or-timeout.tsx
- packages/wallet/src/redux/protocols/challenging/container.tsx
- packages/wallet/src/redux/protocols/challenging/index.ts
- packages/wallet/src/redux/protocols/challenging/readme.md
- packages/wallet/src/redux/protocols/challenging/reducer.ts
- packages/wallet/src/redux/protocols/challenging/states.ts
- packages/wallet/src/redux/protocols/indirect-funding/reducer-helpers.ts
- packages/wallet/src/redux/protocols/transaction-submission/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/transaction-submission/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/transaction-submission/actions.ts
- packages/wallet/src/redux/protocols/transaction-submission/index.ts
- packages/wallet/src/redux/protocols/transaction-submission/states.ts
- packages/wallet/src/redux/state.ts
Does most of the challenging protocol. Thought it would be a good time to merge though.
Still to do:
> Challenging

- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/protocols/direct-funding/actions.ts
- packages/wallet/src/redux/protocols/funding/actions.ts
- packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/funding/player-a/actions.ts
- packages/wallet/src/redux/protocols/funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/funding/player-a/states.ts
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/funding/player-b/actions.ts
- packages/wallet/src/redux/protocols/funding/player-b/reducer.ts
- packages/wallet/src/redux/protocols/funding/player-b/states.ts
- packages/wallet/src/redux/protocols/funding/states.ts
- packages/wallet/src/redux/protocols/index.ts
- packages/wallet/src/redux/protocols/indirect-funding/actions.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts
> Funding protocol work

- packages/wallet/src/redux/protocols/challenging/states.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/direct-funding/reducer.ts
- packages/wallet/src/redux/protocols/direct-funding/state.ts
- packages/wallet/src/redux/protocols/responding/reducer.ts
- packages/wallet/src/redux/protocols/responding/state.ts
- packages/wallet/src/redux/protocols/transaction-submission/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/transaction-submission/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/transaction-submission/container.tsx
- packages/wallet/src/redux/protocols/transaction-submission/index.ts
- packages/wallet/src/redux/protocols/transaction-submission/readme.md
- packages/wallet/src/redux/protocols/transaction-submission/reducer.ts
- packages/wallet/src/redux/protocols/transaction-submission/states.ts
- packages/wallet/src/redux/protocols/withdrawing/reducer.ts
- packages/wallet/src/redux/protocols/withdrawing/states.ts
- packages/wallet/src/redux/utils.ts
Makes a few improvements to the transaction-submission protocol, updating it to the style used in later protocols.
> Update transaction submission

- packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/funding/player-a/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/funding/player-a/states.ts
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/funding/readme.md
- packages/wallet/src/redux/protocols/indirect-funding/actions.ts
- packages/wallet/src/redux/state.ts
- Removes post-fund-setup requirements from funding protocol
- Implements the player-a reducer (except for the waitForFunding state)
> player A funding protocol reducer

- packages/wallet/src/redux/protocols/actions.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts
- packages/wallet/src/redux/reducer.ts
- packages/wallet/src/redux/sagas/message-listener.ts
Fixes https://github.com/magmo/apps/issues/419.
> Actions that spin up a new process

- packages/wallet/src/redux/__tests__/test-scenarios.ts
- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/channel-store/reducer.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/index.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/direct-funding/reducer.ts
- packages/wallet/src/redux/sagas/message-listener.ts
- packages/wallet/src/redux/state.ts
- packages/wallet/src/utils/commitment-utils.ts
Fixes https://github.com/magmo/apps/issues/404.
> Wire up direct funding protocol with channel store

- packages/wallet/src/containers/initialized.tsx
- packages/wallet/src/redux/protocols/application/actions.ts
- packages/wallet/src/redux/protocols/application/index.ts
- packages/wallet/src/redux/protocols/application/reducer.ts
- packages/wallet/src/redux/protocols/container.tsx
- packages/wallet/src/redux/reducer.ts
- Changed some plumbing so the app protocol works correctly
- Add basic ProtocolContainer so we can see the funding views again
> Changes to get Funding Process Working

- packages/wallet/src/components/acknowledge-x.tsx
- packages/wallet/src/components/approve-x.tsx
- packages/wallet/src/components/checklist.tsx
- packages/wallet/src/components/funding/a-wait-for-post-fund-setup.tsx
- packages/wallet/src/components/funding/b-wait-for-post-fund-setup.tsx
- packages/wallet/src/components/submit-x.tsx
- packages/wallet/src/components/transaction-failed.tsx
- packages/wallet/src/components/wait-for-other-player.tsx
- packages/wallet/src/components/wait-for-x-confirmation.tsx
- packages/wallet/src/components/wait-for-x-initiation.tsx
- packages/wallet/src/containers/metamask-error.tsx
- packages/wallet/src/containers/wallet.tsx
- packages/wallet/src/redux/protocols/direct-funding/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/funding/player-a/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/stories.tsx
I took a global view over storybook and tried to make things more consistent. 
Fixed these problems:
> Clean-up storybook

- packages/wallet/src/redux/protocols/indirect-funding/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/index.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/stories.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-b/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-b/index.ts
> Views for indirect-funding

- packages/wallet/src/redux/protocols/indirect-funding/player-a/components/funding-step.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-a/container.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-b/components/funding-step.tsx
- packages/wallet/src/redux/protocols/indirect-funding/player-b/container.tsx
> Indirect-funding screens

- .circleci/config.yml
- packages/server/src/app/services/rps-commitment.ts
This is a bit nasty, but I was not able to get yarn workspaces to work.
> Cache dependencies for each package

- packages/wallet/src/communication/__tests__/commitments.ts
- packages/wallet/src/communication/__tests__/test-scenarios.ts
- packages/wallet/src/communication/actions.ts
- packages/wallet/src/communication/index.ts
- packages/wallet/src/redux/__tests__/helpers.ts
- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/outbox/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/actions.ts
- packages/wallet/src/redux/protocols/concluding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/concluding/reducer.ts
- packages/wallet/src/redux/protocols/direct-funding/reducer.ts
- packages/wallet/src/redux/protocols/funding/player-a/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/funding/player-a/actions.ts
- packages/wallet/src/redux/protocols/funding/player-b/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-a/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts
- packages/wallet/src/redux/protocols/reducer-helpers.ts
- packages/wallet/src/redux/protocols/responding/reducer.ts
- packages/wallet/src/redux/sagas/message-listener.ts
- packages/wallet/src/utils/commitment-utils.ts
All references to `messageRelayRequested` are contained in the communication module. Hence, all communication between wallets is defined by this module.
> Communication module

- packages/wallet/src/redux/protocols/funding/actions.ts
> Clean up funding actions

- packages/wallet/src/domain/commitments/__tests__/index.ts
- packages/wallet/src/domain/two-player-consensus-game/index.ts
- packages/wallet/src/redux/__tests__/test-scenarios.ts
- packages/wallet/src/redux/protocols/indirect-defunding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/indirect-defunding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/indirect-defunding/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts
- packages/wallet/src/utils/commitment-utils.ts
- packages/wallet/truffle.js
This is a rough start on getting the indirect funding working with the latest consensus app changes.
> Start on getting Indirect Funding working with new Consensus App

- packages/wallet/src/communication/__tests__/test-scenarios.ts
- packages/wallet/src/communication/actions.ts
- packages/wallet/src/communication/index.ts
- packages/wallet/src/redux/protocols/actions.ts
- packages/wallet/src/redux/protocols/concluding/instigator/__tests__/reducer.test.ts
- packages/wallet/src/redux/reducer.ts
Actions that are communicated should be defined in the communication module.
> Move ConcludeInstigated to communication module

- packages/rps/src/components/WeaponSelectedPage.tsx
- packages/wallet/package.json
- packages/wallet/src/contract-tests/adjudicator-events.test.ts
- packages/wallet/src/contract-tests/test-utils.ts
- packages/wallet/src/redux/actions.ts
- packages/wallet/src/redux/adjudicator-state/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/challenging/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/challenging/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/challenging/reducer.ts
- packages/wallet/src/redux/sagas/adjudicator-watcher.ts
- yarn.lock
See https://github.com/magmo/force-move-protocol/pull/65
> Call checkAndStore when in receipt of challenge commitment

- packages/server/.vscode/launch.json
Helpful for setting breakpoints to debug locally.
> VSCode server run configuration

- packages/server/src/wallet/adjudicator-watcher/__chain-test__/adjudicator-watcher.test.ts
Hoping to address this Circle failure: https://circleci.com/gh/magmo/apps/1965
> Making the adjudicator watcher test synchronous

- packages/wallet/src/communication/actions.ts
- packages/wallet/src/domain/commitments/index.ts
- packages/wallet/src/domain/signing-utils.ts
- packages/wallet/src/redux/__tests__/helpers.ts
- packages/wallet/src/redux/__tests__/test-scenarios.ts
- packages/wallet/src/redux/channel-store/channel-state/states.ts
- packages/wallet/src/redux/channel-store/channel-state/valid-transition.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/advance-channel/reducer.ts
- packages/wallet/src/redux/protocols/advance-channel/states.ts
- packages/wallet/src/utils/__tests__/signing-utils.test.ts
I think that the initialization logic is complete, but it is not yet tested for the hub. I am adding tests for the scenarios in order.
> WIP: Initializing the advance-channel protocol

- packages/wallet/src/redux/__tests__/helpers.ts
- packages/wallet/src/redux/channel-store/channel-state/states.ts
- packages/wallet/src/redux/channel-store/reducer.ts
- packages/wallet/src/redux/channel-store/state.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/advance-channel/readme.md
- packages/wallet/src/redux/protocols/advance-channel/reducer.ts
- packages/wallet/src/redux/protocols/advance-channel/states.ts
- packages/wallet/src/redux/protocols/application/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-a/reducer.ts
- packages/wallet/src/redux/protocols/indirect-funding/player-b/reducer.ts
- packages/wallet/src/redux/state.ts
All PreFundSetup tests pass for all three players.
I believe the entire logic is now almost correct, aside from the missing `initializeWithExistingChannel`.
> WIP: Advance channel reducer

- packages/server/src/app/handlers/handle-ongoing-process-action.ts
- packages/server/src/app/routes/v2/channels.ts
the most current `magmo-wallet` can now play RPS against the bot again!
> Handle new relayable actions

- packages/wallet/src/redux/__tests__/helpers.ts
- packages/wallet/src/redux/outbox/reducer.ts
- packages/wallet/src/redux/outbox/state.ts
- packages/wallet/src/redux/protocols/concluding/instigator/__tests__/reducer.test.ts
See commit messages and comments.
> Improve commitment test helpers

- packages/wallet/src/domain/commitments/__tests__/index.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/index.ts
- packages/wallet/src/redux/protocols/advance-channel/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/advance-channel/reducer.ts
- packages/wallet/src/redux/protocols/advance-channel/states.ts
- packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/index.ts
- packages/wallet/src/redux/protocols/virtual-funding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/virtual-funding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/virtual-funding/actions.ts
- packages/wallet/src/redux/protocols/virtual-funding/readme.md
- packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
- packages/wallet/src/redux/protocols/virtual-funding/states.ts
- packages/wallet/src/redux/state.ts
This is a start towards the virtual-funding protocol, to get some things fleshed out.
> WIP: Virtual funding protocol

- packages/wallet/src/redux/protocols/new-ledger-funding/reducer.ts
- packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
A small change broke funding by starting ledger channels with a propose commitment instead of a consensus commitment.
Fixes #606
> Get Funding working

- packages/rps/src/redux/message-service/saga.ts
- packages/wallet/src/redux/protocols/new-ledger-funding/reducer.ts
A race condition was occurring when a post fund setup arrived before the `FundingReceivedEvent`. The `AdvanceChannel` protocol would be passed the post fund setup but there was no check if the `AdvanceChannel` was successful so the `NewLedgerFunding` protocol got stuck in `WaitForPostFundSetup`.
The message saga was also updated to handle sending multiple commitments.
Fixes #609.
> Fix Funding Race Condition

- packages/server/src/app/handlers/handle-ongoing-process-action.ts
> Send messages to next participant in round

- packages/wallet/notes/index.md
- packages/wallet/src/redux/protocols/existing-ledger-funding/readme.md
- packages/wallet/src/redux/protocols/indirect-funding/readme.md
- packages/wallet/src/redux/protocols/new-ledger-channel/readme.md
- packages/wallet/src/redux/protocols/new-ledger-channel/reducer.ts
- packages/wallet/src/redux/protocols/new-ledger-channel/states.ts
> Minor tweaks to documentation for #617

- packages/wallet/notes/index.md
Update notes to reflect our protocol hierarchy.
> Slight update to protocol hierarchy

- packages/wallet/src/redux/protocols/concluding/instigator/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/concluding/instigator/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/concluding/instigator/reducer.ts
Handles a consensus update commitment coming in early.
Fixes #624
> Handle Commitment out of order in Concluding

- packages/server/.vscode/launch.json
- packages/server/src/hub/server.ts
- packages/server/src/message/firebase-relay.ts
Fixed the firebase relay to properly send the messages
> Fix firebase sending

- packages/wallet/.env
- packages/wallet/config/env.js
- packages/wallet/src/constants.ts
- packages/wallet/src/redux/store.ts
During testing it can be convenient to disable storing and loading from indexedDB. I've added a simple flag that does this.
> Add flag to control storage

- packages/wallet/src/communication/index.ts
- packages/wallet/src/constants.ts
- packages/wallet/src/redux/protocols/index.ts
- packages/wallet/src/redux/protocols/virtual-defunding/__tests__/index.ts
- packages/wallet/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts
- packages/wallet/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts
- packages/wallet/src/redux/protocols/virtual-defunding/actions.ts
- packages/wallet/src/redux/protocols/virtual-defunding/container.tsx
- packages/wallet/src/redux/protocols/virtual-defunding/index.ts
- packages/wallet/src/redux/protocols/virtual-defunding/readme.md
- packages/wallet/src/redux/protocols/virtual-defunding/reducer.ts
- packages/wallet/src/redux/protocols/virtual-defunding/states.ts
- packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
- packages/wallet/src/redux/state.ts
Adds a protocol to defund a virtually funded channel.
Fixes #654.
> Virtual De-funding

- packages/wallet/src/redux/__tests__/initialized.test.ts
- packages/wallet/src/redux/protocols/application/reducer.ts
- packages/wallet/src/redux/protocols/application/states.ts
- packages/wallet/src/redux/protocols/concluding/container.tsx
- packages/wallet/src/redux/protocols/concluding/instigator/states.ts
- packages/wallet/src/redux/protocols/concluding/responder/states.ts
- packages/wallet/src/redux/protocols/concluding/states.ts
- packages/wallet/src/redux/protocols/defunding/states.ts
- packages/wallet/src/redux/protocols/funding/states.ts
- packages/wallet/src/redux/reducer.ts
- packages/wallet/src/redux/state.ts
Fixes #653.
Removes processes when they're done.
> Remove process when its done
